/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "tertiary": "#3b525d",
        "inverse-surface": "#2f312e",
        "secondary-fixed": "#ffdbce",
        "surface-tint": "#476550",
        "on-primary-container": "#ccedd3",
        "surface-dim": "#dadad5",
        "on-secondary-container": "#795c51",
        "surface-container": "#eeeee9",
        "on-surface": "#1a1c19",
        "on-tertiary": "#ffffff",
        "surface-bright": "#fafaf5",
        "primary-fixed": "#c9ebd1",
        "surface-container-low": "#f4f4ef",
        "secondary-container": "#fed7ca",
        "background": "#fafaf5",
        "inverse-on-surface": "#f1f1ec",
        "surface": "#fafaf5",
        "surface-container-high": "#e8e8e3",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "surface-container-highest": "#e3e3de",
        "on-secondary-fixed-variant": "#5b4137",
        "outline": "#727972",
        "on-surface-variant": "#424843",
        "on-tertiary-container": "#d0e9f7",
        "on-primary-fixed": "#032111",
        "tertiary-fixed": "#cde6f4",
        "surface-variant": "#e3e3de",
        "on-background": "#1a1c19",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#051e28",
        "tertiary-container": "#526a75",
        "on-primary-fixed-variant": "#304d3a",
        "primary": "#375541",
        "tertiary-fixed-dim": "#b1cad7",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#e4beb2",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#aecfb5",
        "on-tertiary-fixed-variant": "#334a55",
        "inverse-primary": "#aecfb5",
        "primary-container": "#4f6d58",
        "secondary": "#75584d",
        "outline-variant": "#c2c8c1",
        "on-secondary-fixed": "#2b160f"
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}